### PR TITLE
fix for "hide text" option (orange text still appearing)

### PR DESCRIPTION
**Pull request by AbsolutelyFreeWeb**
This patch fixes an issue were new words would still be visible in orange even if the "hide text" option was enable.

### CODE REVIEW

**Comment by camiloaa** [comment]
Nice! I never had time to fix that issue. Can you please increase the version number?

**Review by camiloaa — COMMENTED** [review]
Also write the commit message in a more general way, something like: 

This patch fixes an issue were new words would still be visible in orange even if the "hide text" option was enable.

(Just better redacted)

**Comment by AbsolutelyFreeWeb** [comment]
done. I also made sure "allow edits from maintainers" is set

**Comment by camiloaa** [comment]
Squash and merge locally.

**Pull request closed without merging**
