### PR TITLE
new words are now covered up

### PR DESCRIPTION
**Pull request by ellemcfarlane**
Previously, new words were not covered up as they belong to a new class. With a minor tweak they are now covered up.

### CODE REVIEW

**Review by camiloaa — CHANGES_REQUESTED** [review]
This would mean the old code for this will be dead, right?  Could you remove it and test?

```
diff --git a/DuolingoTreeEnhancer.user.js b/DuolingoTreeEnhancer.user.js
--- a/DuolingoTreeEnhancer.user.js
+++ b/DuolingoTreeEnhancer.user.js
@@ -385,11 +385,6 @@ function challengeTranslate() {
     }
 
     if (isHideText(question)) {
-        newWords = document.getElementsByClassName("MUGWy")
-        if (newWords.length > 0) {
-            newWordsArray = [].slice.call(newWords)
-            newWordsArray.map(element => { element.className = element.className.replace(/MUGWy/g, "");})
-        }
         addCSSHiding(challenge, css_hiding);
     }
 
```

**Comment by ellemcfarlane** [comment]
Meant to double check you didn't have old code doing this. I ended up just slightly modifying your old code to find the new class for the new words Duo must have changed. I so wish you would open an issues tab, so we could work on small things like that.

**Review by camiloaa — CHANGES_REQUESTED** [review]
Could you increment the version number?

**Review by camiloaa — APPROVED** [review]
Thank you very much for your contribution!

**Pull request merged**
